# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 16:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripper', '0004_charge_charge_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=models.CharField(default='usd', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charge',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='charge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='charge_id',
            field=models.CharField(default='', help_text="The Stripe Charge object's ID", max_length=100),
        ),
    ]
