# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripper', '0005_auto_20170622_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='charge_id',
        ),
        migrations.AddField(
            model_name='charge',
            name='stripe_id',
            field=models.CharField(blank=True, default='', help_text="The Stripe Charge object's ID", max_length=100, null=True),
        ),
    ]
