# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripper', '0006_auto_20170622_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='response',
            new_name='stripe_response',
        ),
    ]
