# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='The SOCAN member number submitted in the request.', max_length=16)),
                ('legal_name', models.CharField(max_length=200)),
                ('response_code', models.CharField(max_length=10)),
                ('is_successful', models.BooleanField(default=False)),
            ],
        ),
    ]
