# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import internal.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inconcert', '0002_auto_20200213_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('credit_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[internal.validators.non_negative])),
                ('premium_months', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inconcert.Artist')),
                ('referrer', models.ForeignKey(blank=True, default=None, help_text='The user who invited this user to inConcert, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inconcert_referrals', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inconcert_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
