# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
