# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-18 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0004_auto_20200217_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pre_registration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inconcert.PreRegistration'),
        ),
    ]
