# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0005_profile_pre_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='genreparent',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='genreparent',
            name='parent',
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text="The artist's genre tags", related_name='inconcert_artists', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text="The venue's genre tags", related_name='inconcert_venues', to='core.Genre'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='GenreParent',
        ),
    ]
