# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0297_auto_20200402_2304'),
        ('inconcert', '0006_auto_20200402_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('facebook', models.URLField(blank=True, default=None, null=True)),
                ('messenger', models.URLField(blank=True, default=None, null=True)),
                ('twitter', models.URLField(blank=True, default=None, null=True)),
                ('instagram', models.URLField(blank=True, default=None, null=True)),
                ('spotify', models.URLField(blank=True, default=None, null=True)),
                ('soundcloud', models.URLField(blank=True, default=None, null=True)),
                ('bandcamp', models.URLField(blank=True, default=None, null=True)),
                ('youtube', models.URLField(blank=True, default=None, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('picture', models.URLField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('location_text', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(help_text='The artist to be updated.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='inconcert.Artist')),
                ('genres', models.ManyToManyField(blank=True, help_text="The artist's genre tags", to='core.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VenueUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('facebook', models.URLField(blank=True, default=None, null=True)),
                ('messenger', models.URLField(blank=True, default=None, null=True)),
                ('twitter', models.URLField(blank=True, default=None, null=True)),
                ('instagram', models.URLField(blank=True, default=None, null=True)),
                ('spotify', models.URLField(blank=True, default=None, null=True)),
                ('soundcloud', models.URLField(blank=True, default=None, null=True)),
                ('bandcamp', models.URLField(blank=True, default=None, null=True)),
                ('youtube', models.URLField(blank=True, default=None, null=True)),
                ('website', models.URLField(blank=True, default=None, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('picture', models.URLField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=10000, null=True)),
                ('location_text', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, help_text="The venue's genre tags", to='core.Genre')),
                ('venue', models.ForeignKey(help_text='The venue to be updated.', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='inconcert.Venue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
