# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0297_auto_20200402_2304'),
        ('inconcert', '0007_artistupdate_venueupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_venue', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.City')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.Genre')),
                ('user', models.ForeignKey(help_text='The user who submitted the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
