# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 02:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0008_userquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='user',
            field=models.ForeignKey(default=None, help_text='The user who submitted the request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
