# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0009_auto_20200403_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.City'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='genre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='core.Genre'),
        ),
    ]
