# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-03 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0010_auto_20200403_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='is_artist',
        ),
        migrations.RemoveField(
            model_name='userquery',
            name='is_venue',
        ),
        migrations.AddField(
            model_name='userquery',
            name='model',
            field=models.IntegerField(choices=[(0, 'ARTIST'), (1, 'VENUE')], default=0),
        ),
    ]
