# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-16 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0012_userquery_results_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credit_balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='has_lifetime_membership',
            field=models.BooleanField(default=False),
        ),
    ]
