# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-22 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0013_auto_20200416_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pre_registration',
        ),
        migrations.DeleteModel(
            name='PreRegistration',
        ),
    ]
