# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0015_auto_20200524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium_months',
            field=models.IntegerField(default=0),
        ),
    ]
