# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0016_auto_20200524_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_paid_membership',
            field=models.BooleanField(default=False),
        ),
    ]
