# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-08 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0022_artistimport_eventimport_venueimport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistimport',
            options={'verbose_name_plural': '(Import) Artists'},
        ),
        migrations.AlterModelOptions(
            name='eventimport',
            options={'verbose_name_plural': '(Import) Events'},
        ),
        migrations.AlterModelOptions(
            name='venueimport',
            options={'verbose_name_plural': '(Import) Venues'},
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='accessibility_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='affiliation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='artists_we_also_like',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='atory',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='attire',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='awards',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='band_interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='band_members',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='bandcamp',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='biography',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='booking_agent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='company_overview',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='culinary_team',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='current_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='directed_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='facebook',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='founding_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='gender',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='general_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='general_manager',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='genre',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='hometown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='impressum',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='influences',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='instagram',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='likes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='members',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='misc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='mission',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='network',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='page_created',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='page_types',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='personal_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='personal_interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='plot_outline',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='press_contact',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='price_range',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='products',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='public_transit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='record_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='release_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='schedule',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='season',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='soundcloud',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='spotify',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='starring',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='twitter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='website',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='written_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artistimport',
            name='youtube',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='eventimport',
            name='event_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='eventimport',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='eventimport',
            name='profile_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='about',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='accessibility_info',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='affiliation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='artists_we_also_like',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='atory',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='attire',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='awards',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='band_interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='band_members',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='bandcamp',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='biography',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='booking_agent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='company_overview',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='culinary_team',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='current_location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='directed_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='facebook',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='founding_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='gender',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='general_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='general_manager',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='genre',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='hometown',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='impressum',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='influences',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='instagram',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='likes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='members',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='misc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='mission',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='network',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='page_created',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='page_types',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='personal_information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='personal_interests',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='phone',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='plot_outline',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='press_contact',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='price_range',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='products',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='public_transit',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='record_label',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='release_date',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='schedule',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='season',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='soundcloud',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='spotify',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='starring',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='twitter',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='website',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='written_by',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='venueimport',
            name='youtube',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
