# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0023_auto_20200608_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genres_text',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='likes_text',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='likes_text',
        ),
        migrations.AddField(
            model_name='artist',
            name='import_data',
            field=models.ForeignKey(blank=True, default=None, help_text='Raw fields from extraction.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inconcert.ArtistImport'),
        ),
        migrations.AddField(
            model_name='artistimport',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, default=None, help_text='Link to facebook event.', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='import_data',
            field=models.ForeignKey(blank=True, default=None, help_text='Raw fields from extraction.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inconcert.VenueImport'),
        ),
        migrations.AddField(
            model_name='venueimport',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, help_text='Not used.', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(blank=True, default=None, help_text='Not used.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='fans_interested',
            field=models.IntegerField(blank=True, default=None, help_text='Count of fans who showed interest. Not used.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='fans_went',
            field=models.IntegerField(blank=True, default=None, help_text='Count of fans who attended. Not used.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Not used.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.URLField(blank=True, default=None, help_text='Not used.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(blank=True, default=None, help_text='Not used.', null=True),
        ),
    ]
