# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-14 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0024_auto_20200614_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistimport',
            old_name='atory',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='venueimport',
            old_name='atory',
            new_name='story',
        ),
    ]
