# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-02 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inconcert', '0025_auto_20200614_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimport',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
    ]
