# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_band_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pledge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
