# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170512_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[[0, 'GOAL_AMOUNT'], [1, 'GOAL_COUNT'], [2, 'INSTANT_SALE']], default=1),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_count',
            field=models.IntegerField(default=0),
        ),
    ]
