# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170516_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='seating_type',
            field=models.IntegerField(choices=[[0, 'FIRST_COME_FIRST_SEATING']], default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[[0, 'GOAL_COUNT'], [1, 'GOAL_AMOUNT'], [2, 'INSTANT_SALE']], default=0),
        ),
    ]
