# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170604_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='artist',
            new_name='is_artist',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='venue',
            new_name='is_venue',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been confirmed"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
