# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripper', '0009_customer_email'),
        ('core', '0011_auto_20170606_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='pledge_amount',
        ),
        migrations.AddField(
            model_name='pledge',
            name='count',
            field=models.IntegerField(default=1, help_text='The number of tickets a person has pledge to buy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stripper.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='The price at which a person has pledge to buy tickets', max_digits=6),
            preserve_default=False,
        ),
    ]
