# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170623_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='bands',
            field=models.ManyToManyField(to='core.CampaignBand'),
        ),
    ]
