# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170623_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignband',
            name='profit_share',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
