# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_campaignband_profit_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pledge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.Pledge'),
            preserve_default=False,
        ),
    ]
