# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pledge_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='price',
        ),
        migrations.AddField(
            model_name='pledge',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total amount that the user has pledged', max_digits=6, verbose_name='Total amount pledged'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pledge',
            name='bands',
            field=models.ManyToManyField(to='core.CampaignBand', verbose_name='Going to see'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='count',
            field=models.IntegerField(help_text='The number of tickets the user will receive should the campaign succeed', verbose_name='Number of tickets'),
        ),
    ]
