# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20170623_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pledge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
