# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20170623_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='successful',
            field=models.BooleanField(default=False, help_text='Whether the campaign has been fully funded or not'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[[0, 'GOAL_AMOUNT']], default=0),
        ),
    ]
