# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170630_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(choices=[('cad', 'CAD')], default='cad', help_text='The currency that the campaign will operate in', max_length=3),
        ),
    ]
