# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_campaign_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_email',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_location',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[(0, 'GOAL_AMOUNT')], default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='seating_type',
            field=models.IntegerField(choices=[(0, 'FIRST_COME_FIRST_SEATING')], default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default=None, help_text='The unique ticket number', max_length=16),
        ),
    ]
