# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170630_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default='2d62c9595f1c77666692fe5d8fbb7b9e', help_text='The unique ticket number', max_length=16),
        ),
    ]
