# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170630_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='f7562e100ff5aa11', help_text='The unique ticket code', max_length=16),
        ),
    ]
