# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170701_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='dc39966d1d162a7a', help_text='The unique ticket code', max_length=16),
        ),
    ]
