# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170725_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='daeadb0e5af73403', help_text='The unique ticket code', max_length=16),
        ),
    ]
