# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-30 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20170729_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='5c8db8a7c10a6936', help_text='The unique ticket code', max_length=16),
        ),
    ]
