# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20170806_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='7a86c0cc9c9b925b', help_text='The unique ticket code', max_length=16),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='last_day',
            field=models.DateTimeField(blank=True, help_text='The last day this timeslot may be booked', null=True),
        ),
    ]
