# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-11 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20170806_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='1aacfcc8a8d9466d', help_text='The unique ticket code', max_length=16),
        ),
    ]
