# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20170811_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='description',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='a85d29c713892a8e', help_text='The unique ticket code', max_length=16),
        ),
    ]
