# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20170813_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='25e45a0953edd47b', help_text='The unique ticket code', max_length=16),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
