# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20170813_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('photo', models.ImageField(upload_to='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.Campaign')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='613d189f40b34655', help_text='The unique ticket code', max_length=16),
        ),
    ]
