# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 17:21
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20170813_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(max_length=2000, validators=[core.validators.validate_markdown]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='64e4994a5b75ec67', help_text='The unique ticket code', max_length=16),
        ),
    ]
