# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20170819_1721'),
        ('core', '0045_auto_20170819_1751'),
    ]

    operations = [
    ]
