# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0047_auto_20170819_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='band',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='The user that created the band', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='code',
            field=models.CharField(default='c8d1a493de861909', help_text='The unique ticket code', max_length=16),
        ),
    ]
