# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20170820_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={},
        ),
        migrations.AddField(
            model_name='band',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
