# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20170820_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='confirmed',
            new_name='is_confirmed',
        ),
        migrations.RenameField(
            model_name='band',
            old_name='created_by',
            new_name='creator',
        ),
    ]
