# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20170820_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='artist',
            name='is_accepted',
            field=models.NullBooleanField(default=False, help_text='Whether the user has confirmed that they are in the band'),
        ),
    ]
