# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20170820_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='is_accepted',
            field=models.NullBooleanField(default=None, help_text='Whether the user has confirmed that they are in the band'),
        ),
    ]
