# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-20 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20170820_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='updated_at',
        ),
    ]
