# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20170820_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether to include the campaign on the home page or not..'),
        ),
    ]
