# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_band_is_featured'),
        ('core', '0060_campaign_is_featured'),
    ]

    operations = [
    ]
