# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_band_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='currency',
        ),
        migrations.AddField(
            model_name='venue',
            name='currency',
            field=models.CharField(choices=[('cad', 'CAD')], default='cad', help_text='The currency that the venue operates in', max_length=3),
        ),
    ]
