# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20170826_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[(0, 'GOAL_AMOUNT'), (1, 'GOAL_COUNT')], default=0),
        ),
    ]
