# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20170906_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_venue_approved',
            field=models.NullBooleanField(default=None, help_text='Whether the venue has confirmed the campaign'),
        ),
    ]
