# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='hashtag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
