# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20171010_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
