# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_campaign_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AddField(
            model_name='campaign',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
