# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0069_campaign_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set([('user', 'band')]),
        ),
    ]
