# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20171013_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together=set([]),
        ),
    ]
