# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 15:44
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_merge_20171013_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
        migrations.AddField(
            model_name='venue',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='min_headcount',
            field=models.IntegerField(validators=[core.validators.non_negative]),
        ),
    ]
