# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20171017_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether to include the venue on the home page or not..'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='core.City'),
        ),
    ]
