# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 20:26
from __future__ import unicode_literals

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20171022_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='America/Toronto'),
        ),
    ]
