# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 03:22
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_venue_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='allows_all_ages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='allows_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_atm_nearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_back_load_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_drum_kit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_free_parking_nearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_front_load_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_microphones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_paid_parking_nearby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_piano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='has_wires_and_cables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_accessible_by_transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_wheelchair_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
