# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_venue_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Whether the campaign bands may change or not'),
        ),
    ]
