# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_auto_20171214_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='currency',
            field=models.CharField(choices=[('cad', 'CAD'), ('usd', 'USD')], default='cad', help_text='The currency that the venue operates in', max_length=3),
        ),
    ]
