# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_campaign_is_open'),
        ('core', '0079_auto_20180102_2131'),
    ]

    operations = [
    ]
