# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20180208_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='success_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
