# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_campaign_success_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='soundcloud_link',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='twitter_link',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='web_link',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='band',
            name='bandcamp',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='soundcloud',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='spotify',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='youtube',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='bandcamp',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='soundcloud',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='spotify',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='twitter',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='youtube',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
