# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20180305_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='extra_details',
            field=models.TextField(blank=True, help_text='Anything else we should know?', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='when',
            field=models.TextField(blank=True, help_text='When do you want to play?', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='who',
            field=models.TextField(blank=True, help_text='Who do you want to play with?', max_length=2000, null=True),
        ),
    ]
