# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_jobrunnercheckin'),
        ('core', '0088_auto_20180310_0310'),
    ]

    operations = [
    ]
