# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_bookingrequest_is_crowdfunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='is_redpine',
            field=models.BooleanField(default=True),
        ),
    ]
