# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_bookingrequest_is_crowdfunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Whether to include the venue in search results or not..'),
        ),
    ]
