# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_venue_is_hidden'),
        ('core', '0091_auto_20180322_1731'),
    ]

    operations = [
    ]
