# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20180322_1626'),
        ('core', '0092_merge_20180323_1934'),
    ]

    operations = [
    ]
