# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_merge_20180327_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('strength', models.IntegerField(default=0, help_text='Relation strength between the two bands.')),
                ('band_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bands', to='core.Band')),
                ('band_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='more_related_bands', to='core.Band')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='')),
                ('clip_start', models.IntegerField(default=0, help_text='Number of seconds into the song to start preview.')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.Band')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=200)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Band')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Track')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
