# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_merge_20180329_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='hometown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='core.City'),
        ),
    ]
