# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_bandlink_track_trackcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcomment',
            name='is_positive',
            field=models.NullBooleanField(default=None),
        ),
    ]
