# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_auto_20180415_2245'),
        ('core', '0095_trackcomment_is_positive'),
    ]

    operations = [
    ]
