# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_merge_20180418_0058'),
        ('core', '0094_band_hometown'),
    ]

    operations = [
    ]
