# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_auto_20180422_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='max_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, help_text='A description for tickets with special privileges', max_length=500, null=True),
        ),
    ]
