# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_auto_20180423_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_count',
            field=models.IntegerField(default=0, help_text='Should not be 0 unless the show is direct-booked, even if the funding condition is GOAL_AMOUNT.'),
        ),
    ]
