# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20180516_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandtobandreview',
            name='communication',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Did the band communicate effectively when required?'),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='draw',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Did the band accurately represent their draw?'),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='ease_of_working',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Was the band easy to work with?'),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='overall',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='communication',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Did the venue communicate effectively when required?'),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='ease_of_working',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Was the venue easy to work with?'),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='equipment',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Did the venue accurately represent the variety and quality of their equipment?'),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='overall',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='communication',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Did the band communicate effectively when required?'),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='draw',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Did the band accurately represent their draw?'),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='ease_of_working',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2, help_text='Was the band easy to work with?'),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='overall',
            field=models.IntegerField(choices=[(0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=2),
        ),
    ]
