# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_campaignfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='has_door_plan',
            field=models.BooleanField(default=False, help_text='The artists and venue have agreed on how doors should be handled.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_equipment_plan',
            field=models.BooleanField(default=False, help_text='The artists and venue are aware of their equipment responsibilities.'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_event_page',
            field=models.BooleanField(default=False, help_text='The artists have created an event page for the show'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_group_chat',
            field=models.BooleanField(default=False, help_text='The artists have made a group chat to coordinate the show'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_set_order',
            field=models.BooleanField(default=False, help_text='The artists have chosen a set order'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_sound_plan',
            field=models.BooleanField(default=False, help_text='The artists and venue have agreed on how sound should be handled.'),
        ),
    ]
