# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_remove_campaign_has_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='setlist',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
