# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_band_setlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignband',
            name='is_accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
