# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_campaignband_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the band', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='venue',
            field=models.ForeignKey(help_text='The venue which is being requested', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.Venue'),
        ),
    ]
