# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20180707_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funding_start',
            field=models.DateTimeField(null=True),
        ),
    ]
