# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20180707_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
