# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20180722_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='join_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
