# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_band_join_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[(0, 'GOAL_AMOUNT'), (1, 'GOAL_COUNT'), (2, 'HYBRID')], default=2),
        ),
    ]
