# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20180801_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignfeed',
            name='sent_notification',
            field=models.BooleanField(default=False),
        ),
    ]
