# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_campaignfeed_sent_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='venue',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
