# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20180906_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
