# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_profile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignband',
            name='expected_draw',
            field=models.IntegerField(default=0, help_text="An act's self-estimated draw."),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
