# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 21:02
from __future__ import unicode_literals

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_auto_20180909_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='communication',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Did the band communicate effectively when required?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='draw',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Did the band accurately represent their draw?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='ease_of_working',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Was the band easy to work with?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtobandreview',
            name='overall',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='communication',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Did the venue communicate effectively when required?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='ease_of_working',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Was the venue easy to work with?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='equipment',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Did the venue accurately represent the variety and quality of their equipment?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='bandtovenuereview',
            name='overall',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='redpine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount that the user has paid to RedPine', max_digits=6, validators=[core.validators.non_negative], verbose_name="RedPine's fee"),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has pledged', max_digits=6, validators=[core.validators.non_negative], verbose_name='Total amount pledged'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The amount to charge for this item', max_digits=6, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=100, help_text='The number of this item available for sale.', validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='communication',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Did the band communicate effectively when required?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='draw',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Did the band accurately represent their draw?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='ease_of_working',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, help_text='Was the band easy to work with?', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='venuetobandreview',
            name='overall',
            field=models.IntegerField(choices=[(-1, 'NULL'), (0, 'ONE_STAR'), (1, 'TWO_STAR'), (2, 'THREE_STAR'), (3, 'FOUR_STAR'), (4, 'FIVE_STAR')], default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
