# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 02:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hold_priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Event', max_length=200),
        ),
    ]
