# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 03:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_auto_20180915_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='hold_priority',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
