# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 17:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_auto_20180915_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hold_priority',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_hold',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
