# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_campaigndocument_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigndocument',
            name='document_type',
        ),
    ]
