# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 12:15
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_notification_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='age_restriction',
            field=models.IntegerField(choices=[(0, 'ALL_AGES'), (1, '19+')], default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='promoter_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[core.validators.non_negative]),
        ),
    ]
