# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 00:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_auto_20180928_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='age_restriction',
            field=models.IntegerField(choices=[(0, 'ALL_AGES'), (1, '19+'), (2, '18+'), (3, '16+')], default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
