# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20181003_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='default_headcount_weekday',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='default_headcount_weekend',
            field=models.IntegerField(default=0),
        ),
    ]
