# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_auto_20181020_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(default='Opening', max_length=200)),
                ('is_open', models.BooleanField(default=0)),
                ('timeslot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opening', to='core.Timeslot')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
