# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-20 15:57
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='min_headcount',
            field=models.IntegerField(default=0, validators=[core.validators.non_negative]),
        ),
    ]
