# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_auto_20181022_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='cash_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='drink_tickets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='float_cash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='merch_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='soundtech',
            field=models.BooleanField(default=False),
        ),
    ]
