# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_auto_20181025_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='meal_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
