# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-26 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_venue_meal_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='meal_voucher',
            new_name='meal_vouchers',
        ),
    ]
