# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-27 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20181026_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_only_tickets',
            field=models.BooleanField(default=False, help_text='For campaigns which do not have a venue relationship.'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_non_redpine_default',
            field=models.BooleanField(default=False, help_text='For ticketed events where the venue is unknown. Like Highlander, there can only be one.'),
        ),
    ]
