# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_auto_20181028_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
