# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0151_auto_20181028_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='current_city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_bands', to='core.City'),
        ),
    ]
