# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0152_band_current_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='is_real',
            field=models.BooleanField(default=True, help_text="Pledges are still created for direct-ticketed events, but they shouldn't be visible in the UI as such."),
        ),
    ]
