# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20181105_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='shows',
            new_name='campaigns',
        ),
    ]
