# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20181127_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='primary_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_venues', to='core.Genre'),
        ),
        migrations.AddField(
            model_name='venue',
            name='secondary_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_venues', to='core.Genre'),
        ),
    ]
