# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_auto_20181212_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignfeed',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
