# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 19:20
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0168_auto_20181212_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='default_fee_weekday',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[core.validators.non_negative]),
        ),
        migrations.AddField(
            model_name='venue',
            name='default_fee_weekend',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[core.validators.non_negative]),
        ),
    ]
