# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_auto_20181212_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='cash_box',
            new_name='has_cash_box',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='drink_tickets',
            new_name='has_drink_tickets',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='float_cash',
            new_name='has_float_cash',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='lighting',
            new_name='has_lighting',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='meal_vouchers',
            new_name='has_meal_vouchers',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='merch_space',
            new_name='has_merch_space',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='soundtech',
            new_name='has_soundtech',
        ),
    ]
