# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20181213_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignband',
            options={},
        ),
    ]
