# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0171_auto_20181217_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='age_restriction',
        ),
        migrations.AddField(
            model_name='campaign',
            name='minimum_age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
