# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_auto_20190128_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignorganization',
            name='can_edit',
            field=models.BooleanField(default=True),
        ),
    ]
