# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-31 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0176_auto_20190125_1704'),
        ('core', '0176_auto_20190129_0305'),
    ]

    operations = [
    ]
