# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0178_auto_20190201_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='join_token',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
