# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0179_auto_20190201_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='band',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='commenter',
        ),
        migrations.RemoveField(
            model_name='trackcomment',
            name='track',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.DeleteModel(
            name='TrackComment',
        ),
    ]
