# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0180_auto_20190205_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandlink',
            name='band_1',
        ),
        migrations.RemoveField(
            model_name='bandlink',
            name='band_2',
        ),
        migrations.DeleteModel(
            name='BandLink',
        ),
    ]
