# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0181_auto_20190205_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='payout_type',
            field=models.IntegerField(choices=[(0, 'ALL_TO_ORGANIZER'), (1, 'SPLIT_BY_ACT_SALES')], default=1),
        ),
    ]
