# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0182_campaign_payout_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BandPayment',
            new_name='ArtistPayment',
        ),
    ]
