# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-05 21:25
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0183_auto_20190205_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[core.validators.non_negative])),
                ('paid', models.BooleanField(default=False)),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Band')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
