# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0185_auto_20190210_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='payouts_processed',
            field=models.BooleanField(default=False, help_text='Whether or not the funds from this pledge have already been distributed to performers.'),
        ),
    ]
