# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0186_pledge_payouts_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_picture', models.ImageField(blank=True, help_text="The image to display on the homepage. If 'None' then a random venue photo will be chosen.", null=True, upload_to='')),
            ],
        ),
    ]
