# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 23:17
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0187_globalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmail',
            options={'verbose_name_plural': 'Zee Mail Cannon'},
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=4, validators=[core.validators.non_negative]),
        ),
    ]
