# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0190_auto_20190228_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='subject',
            field=models.ForeignKey(default=None, help_text='The user who must complete the task for rewards to be paid out.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reward',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
