# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-02 03:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0191_auto_20190301_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='recipient',
            field=models.ForeignKey(help_text='The user who recieves the reward.', on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL),
        ),
    ]
