# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0192_auto_20190302_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='venue_name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=200, null=True),
        ),
    ]
