# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0193_campaign_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='core.Venue'),
        ),
    ]
