# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_bandsubscription_organizationsubscription_venuesubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandsubscription',
            options={'verbose_name_plural': 'Subscriptions (Bands)'},
        ),
        migrations.AlterModelOptions(
            name='organizationsubscription',
            options={'verbose_name_plural': 'Subscriptions (Organizations)'},
        ),
        migrations.AlterModelOptions(
            name='venuesubscription',
            options={'verbose_name_plural': 'Subscriptions (Venues)'},
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_add_act_members',
            field=models.BooleanField(default=False, help_text='Whether or not the user has added other users to their act.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_add_act_socials',
            field=models.BooleanField(default=False, help_text='Whether or not the user has added socials to their act.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_add_event',
            field=models.BooleanField(default=False, help_text='Whether or not the user has tried adding an event or hold for their venue.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_add_opening',
            field=models.BooleanField(default=False, help_text='Whether or not the user has tried adding an opening for their venue.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_add_profile_pic',
            field=models.BooleanField(default=False, help_text='Whether or not the user has added a profile pic.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_approve_booking_request',
            field=models.BooleanField(default=False, help_text='Whether or not the user has approved a booking request.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_create_act',
            field=models.BooleanField(default=False, help_text='Whether or not the user has added an act, or was added to one.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_create_venue',
            field=models.BooleanField(default=False, help_text='Whether or not the user has added a venue, or was added to one.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_submit_booking_request',
            field=models.BooleanField(default=False, help_text='Whether or not the user has requested to book a venue.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_view_my_tickets',
            field=models.BooleanField(default=False, help_text='Whether or not the user has checked out My Tickets.'),
        ),
    ]
