# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0195_bandsubscription_organizationsubscription_venuesubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bandsubscription',
            options={'verbose_name_plural': 'Subscriptions (Bands)'},
        ),
        migrations.AlterModelOptions(
            name='organizationsubscription',
            options={'verbose_name_plural': 'Subscriptions (Organizations)'},
        ),
        migrations.AlterModelOptions(
            name='venuesubscription',
            options={'verbose_name_plural': 'Subscriptions (Venues)'},
        ),
    ]
