# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-26 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0196_auto_20190326_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcashtransaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='bands',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='count',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='payouts_processed',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='redpine_fee',
        ),
        migrations.RemoveField(
            model_name='appcardtransaction',
            name='total',
        ),
        migrations.AlterField(
            model_name='appcashtransaction',
            name='bands',
            field=models.ManyToManyField(to='core.CampaignBand', verbose_name='Going to see'),
        ),
        migrations.AlterField(
            model_name='appcashtransaction',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
    ]
