# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0197_auto_20190328_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='currency',
            field=models.CharField(choices=[('CAD', 'CAD'), ('USD', 'USD')], default='CAD', help_text='The currency that the venue operates in', max_length=3),
        ),
    ]
