# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0198_auto_20190328_0524'),
        ('core', '0197_auto_20190326_2133'),
    ]

    operations = [
    ]
