# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 22:03
from __future__ import unicode_literals

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0199_merge_20190328_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcardtransaction',
            options={},
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='bands',
            field=models.ManyToManyField(to='core.CampaignBand', verbose_name='Going to see'),
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='count',
            field=models.IntegerField(default=0, help_text='The number of tickets the user will receive should the campaign succeed', verbose_name='Number of tickets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='payouts_processed',
            field=models.BooleanField(default=False, help_text='Whether or not the funds from this pledge have already been distributed to performers.'),
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='processed_by',
            field=models.ForeignKey(default=1, help_text='The user who processed the transaction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='redpine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount that the user has paid to RedPine', max_digits=6, validators=[core.validators.non_negative], verbose_name="RedPine's fee"),
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The total amount that the user has pledged', max_digits=6, validators=[core.validators.non_negative], verbose_name='Total amount pledged'),
            preserve_default=False,
        ),
    ]
