# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0200_auto_20190329_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcardtransaction',
            name='client_transaction_id',
            field=models.CharField(blank=True, help_text='The client transaction ID that was created in Square', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appcardtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='The transaction ID that was created in Square', max_length=100, null=True),
        ),
    ]
