# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0201_auto_20190329_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='door_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
