# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0202_campaign_door_code'),
        ('core', '0196_auto_20190323_1800'),
    ]

    operations = [
    ]
