# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0203_merge_20190404_1729'),
        ('core', '0205_iostoken_user'),
    ]

    operations = [
    ]
