# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0206_merge_20190405_0149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IOSToken',
            new_name='PushToken',
        ),
    ]
