# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0209_venuestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledge',
            options={},
        ),
        migrations.AlterField(
            model_name='pledge',
            name='bands',
            field=models.ManyToManyField(to='core.CampaignBand', verbose_name='Going to see'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
    ]
