# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-25 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0210_auto_20190425_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcardtransactionpurchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='appcashtransactionpurchase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pledgepurchase',
            options={},
        ),
        migrations.AlterField(
            model_name='appcardtransactionpurchase',
            name='item',
            field=models.ForeignKey(help_text='The specific item purchased.', on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseItem'),
        ),
        migrations.AlterField(
            model_name='appcashtransactionpurchase',
            name='item',
            field=models.ForeignKey(help_text='The specific item purchased.', on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseItem'),
        ),
        migrations.AlterField(
            model_name='pledgepurchase',
            name='item',
            field=models.ForeignKey(help_text='The specific item purchased.', on_delete=django.db.models.deletion.CASCADE, to='core.PurchaseItem'),
        ),
    ]
