# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-01 14:49
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0211_auto_20190425_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcardtransaction',
            options={'verbose_name_plural': 'Transactions (App) (Card)'},
        ),
        migrations.AlterModelOptions(
            name='appcashtransaction',
            options={'verbose_name_plural': 'Transactions (App) (Cash)'},
        ),
        migrations.AlterModelOptions(
            name='pledge',
            options={'verbose_name_plural': 'Transactions (Web)'},
        ),
        migrations.AlterModelOptions(
            name='venuestats',
            options={'verbose_name_plural': 'Venue Stats'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_count',
            field=models.IntegerField(blank=True, default=None, help_text='The cached ticket count. Should be "None" until after the show date.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_raised',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='The cached revenue total. Should be "None" until after the show date.', max_digits=6, null=True, validators=[core.validators.non_negative]),
        ),
    ]
