# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0213_auto_20190502_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='before_booking_info',
            field=models.CharField(default='', help_text='Extra info which an act should know before booking the venue. (Markdown)', max_length=2000),
        ),
    ]
