# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0216_auto_20190527_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='extra_details',
            field=models.TextField(blank=True, default='Details of this offer have not been publicized. Discuss in the Show Hub, upon acceptance.', max_length=2000, null=True),
        ),
    ]
