# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0217_auto_20190527_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignband',
            name='expected_draw',
        ),
        migrations.AddField(
            model_name='campaignband',
            name='is_application',
            field=models.BooleanField(default=False, help_text='Is the member applying to an opportunity?'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Is the show a puplic opportunity?'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='extra_details',
            field=models.TextField(blank=True, default='Details of this offer have not been publicized. Discuss your arrangement using the Show Hub, upon acceptance.', max_length=2000, null=True),
        ),
    ]
