# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0218_auto_20190610_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignband',
            name='is_application',
            field=models.NullBooleanField(default=False, help_text='Is the member applying to an opportunity?'),
        ),
    ]
