# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0219_auto_20190610_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, help_text='The associated open campaign, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='core.Campaign'),
        ),
    ]
