# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0220_opening_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='opening',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='core.Timeslot'),
        ),
    ]
