# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0221_auto_20190611_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening',
            name='open_mic',
        ),
    ]
