# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 16:41
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0223_auto_20190615_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='third_party_tickets',
            field=models.URLField(blank=True, default=None, help_text="The URL for the event's non-redpine ticketing page.", null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='promoter_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Not used.', max_digits=5, validators=[core.validators.non_negative]),
        ),
    ]
