# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 17:35
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0224_auto_20190619_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='promoter_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject_type',
            field=models.IntegerField(choices=[(0, 'SYSTEM'), (1, 'CAMPAIGN'), (2, 'VENUE'), (3, 'BAND'), (4, 'TICKETS')], default=0),
        ),
    ]
