# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 18:19
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0226_venue_has_fast_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_member_artist',
            field=models.BooleanField(default=False, help_text='Can the artist use member features?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_member_venue',
            field=models.BooleanField(default=False, help_text='Can the venue use member features?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_ultimate_artist',
            field=models.BooleanField(default=False, help_text='Can the artist use ultimate features?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_ultimate_venue',
            field=models.BooleanField(default=False, help_text='Can the venue use ultimate features?'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='promoter_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Not used.', max_digits=5, validators=[core.validators.non_negative]),
        ),
    ]
