# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0228_accountsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Does this subscription currently apply?'),
        ),
    ]
