# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-15 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0229_accountsubscription_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsubscription',
            old_name='paid',
            new_name='is_paid',
        ),
    ]
