# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0014_charge_exchange_rate'),
        ('core', '0231_auto_20190715_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsubscription',
            old_name='is_paid',
            new_name='is_processed',
        ),
        migrations.RemoveField(
            model_name='accountsubscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountsubscription',
            name='square_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='square.Customer'),
        ),
    ]
