# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0232_auto_20190716_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsubscription',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
