# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-19 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0233_accountsubscription_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsubscription',
            name='is_new',
        ),
    ]
