# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-28 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0234_remove_accountsubscription_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='customer',
        ),
        migrations.AddField(
            model_name='pledge',
            name='promoter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
