# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0235_auto_20190728_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='promoter',
        ),
    ]
