# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 03:45
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0236_remove_pledge_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='draw_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[core.validators.non_negative]),
        ),
    ]
