# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 18:12
from __future__ import unicode_literals

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0239_promoterpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='draw_bonus',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='promoter_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[core.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='promoter',
            field=models.ForeignKey(blank=True, default=None, help_text='The user recieving a promoter cut, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sales', to=settings.AUTH_USER_MODEL),
        ),
    ]
