# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0240_auto_20190813_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='processing_failed',
            field=models.BooleanField(default=False),
        ),
    ]
