# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-27 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0241_pledge_processing_failed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='processing_failed',
            new_name='is_processing_failed',
        ),
    ]
