# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_auto_20190827_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_successful',
            field=models.BooleanField(default=True, help_text='Whether the campaign has been fully funded or not'),
        ),
    ]
