# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-30 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_auto_20190829_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='welcome_add_opening',
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_check_calendar',
            field=models.BooleanField(default=False, help_text='Whether or not the user has checked their calendar.'),
        ),
    ]
