# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-12 04:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_auto_20190912_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
