# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-12 16:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0247_auto_20190912_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='depth',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='genre',
            name='parent_genre',
            field=models.ForeignKey(default=None, help_text='The umbrella genre, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Genre'),
        ),
    ]
