# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-12 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_auto_20190912_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='parent_genre',
            new_name='parent',
        ),
    ]
