# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-12 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0249_auto_20190912_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='depth',
        ),
    ]
