# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0251_auto_20190914_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genreparent',
            options={'verbose_name_plural': 'Genre Network'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='parents',
            new_name='genres',
        ),
        migrations.AlterField(
            model_name='genreparent',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='genreparent',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genre'),
        ),
    ]
