# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0252_auto_20190914_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(help_text="The band's genre tags", related_name='bands', to='core.Genre'),
        ),
    ]
