# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0253_band_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='genres',
            field=models.ManyToManyField(help_text="The venue's genre tags", related_name='venues', to='core.Genre'),
        ),
    ]
