# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0255_auto_20190914_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='primary_genre',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='secondary_genre',
        ),
    ]
