# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-14 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0256_auto_20190914_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text="The band's genre tags", related_name='bands', to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text="The venue's genre tags", related_name='venues', to='core.Genre'),
        ),
    ]
