# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 00:05
from __future__ import unicode_literals

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0257_auto_20190914_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledgepurchase',
            old_name='pledge',
            new_name='transaction',
        ),
        migrations.AlterField(
            model_name='appcardtransaction',
            name='payouts_processed',
            field=models.BooleanField(default=False, help_text='Whether or not the funds from this transaction have already been distributed to performers.'),
        ),
        migrations.AlterField(
            model_name='appcardtransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has spent', max_digits=6, validators=[core.validators.non_negative], verbose_name='Total purchase amount'),
        ),
        migrations.AlterField(
            model_name='appcashtransaction',
            name='payouts_processed',
            field=models.BooleanField(default=False, help_text='Whether or not the funds from this transaction have already been distributed to performers.'),
        ),
        migrations.AlterField(
            model_name='appcashtransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has spent', max_digits=6, validators=[core.validators.non_negative], verbose_name='Total purchase amount'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='is_real',
            field=models.BooleanField(default=True, help_text="Pledges are created for direct-ticketed events, but they shouldn't be visible in the UI as such."),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='payouts_processed',
            field=models.BooleanField(default=False, help_text='Whether or not the funds from this transaction have already been distributed to performers.'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has spent', max_digits=6, validators=[core.validators.non_negative], verbose_name='Total purchase amount'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
