# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0258_auto_20190930_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='campaignband',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='campaignorganization',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='discuss_doors',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='discuss_equipment',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='discuss_sound',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='facebook_event',
            field=models.URLField(blank=True, default=None, help_text="The URL for the event's facebook page.", null=True),
        ),
        migrations.AddField(
            model_name='campaignband',
            name='start_time',
            field=models.DateTimeField(default=None, help_text="The time when the act's performance will start.", null=True),
        ),
    ]
