# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0259_auto_20191008_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='discuss_doors',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='discuss_equipment',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='discuss_sound',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
