# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0261_auto_20191009_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignband',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, help_text="The time when the act's performance will start.", null=True),
        ),
    ]
