# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0262_auto_20191011_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='creator',
            new_name='owner',
        ),
    ]
