# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0263_auto_20191014_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='owner',
            field=models.ForeignKey(help_text='The user responsible for the band', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
