# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0264_auto_20191014_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Band')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='bands',
            field=models.ManyToManyField(related_name='organizations', through='core.OrganizationBand', to='core.Band'),
        ),
    ]
