# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0266_auto_20191016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistpayment',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Band'),
        ),
    ]
