# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 21:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0267_auto_20191022_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistPayment',
            new_name='UserPayment',
        ),
    ]
