# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0268_auto_20191022_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='is_crowdfunded',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, help_text='The organization that submitted the request, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted the request', on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='band',
            field=models.ForeignKey(help_text='"None" if RedPine pays.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Band'),
        ),
    ]
