# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0269_auto_20191022_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, help_text='Populated if the payment is directly from a show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='band',
            field=models.ForeignKey(blank=True, default=None, help_text='"None" if RedPine pays.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Band'),
        ),
    ]
