# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 22:25
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0270_auto_20191022_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[core.validators.non_negative])),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator_organization',
            field=models.ForeignKey(blank=True, default=None, help_text='The organization who requested the show, if any.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='payout_type',
            field=models.IntegerField(choices=[(0, 'ALL_TO_ORGANIZER'), (1, 'SPLIT_BY_ACT_SALES'), (2, 'ALL_TO_ORGANIZATION')], default=1),
        ),
        migrations.AddField(
            model_name='organizationpayment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
        migrations.AddField(
            model_name='organizationpayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
    ]
