# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 01:14
from __future__ import unicode_literals

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0271_auto_20191022_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[core.validators.non_negative]),
        ),
    ]
