# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0272_organization_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='actpayment',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Organization'),
        ),
        migrations.AlterField(
            model_name='actpayment',
            name='campaign',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Campaign'),
        ),
    ]
