# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-25 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0274_auto_20191025_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_member_organizer',
            field=models.BooleanField(default=False, help_text='Can the venue use organizer features?'),
        ),
    ]
