# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-29 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0276_auto_20191025_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcardtransaction',
            name='attendee_count',
            field=models.IntegerField(default=0, help_text='How many people showed up?', verbose_name='Number of attendees'),
        ),
        migrations.AddField(
            model_name='appcashtransaction',
            name='attendee_count',
            field=models.IntegerField(default=0, help_text='How many people showed up?', verbose_name='Number of attendees'),
        ),
        migrations.AddField(
            model_name='pledge',
            name='attendee_count',
            field=models.IntegerField(default=0, help_text='How many people showed up?', verbose_name='Number of attendees'),
        ),
    ]
