# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0280_auto_20191104_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='venue_name',
        ),
    ]
