# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-04 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0281_remove_campaign_venue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='timezone',
        ),
    ]
