# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0282_remove_venue_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='band',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='welcome_add_act_members',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
