# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-05 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0283_auto_20191105_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoterpayment',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='promoterpayment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PromoterPayment',
        ),
    ]
