# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0286_auto_20191114_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandtobandreview',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='bandtobandreview',
            old_name='responded',
            new_name='is_responded',
        ),
        migrations.RenameField(
            model_name='bandtovenuereview',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='bandtovenuereview',
            old_name='responded',
            new_name='is_responded',
        ),
        migrations.RenameField(
            model_name='venuetobandreview',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='venuetobandreview',
            old_name='responded',
            new_name='is_responded',
        ),
    ]
