# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0287_auto_20191114_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
