# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0289_auto_20191118_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='badge',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
