# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0292_auto_20191128_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationfeedback',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
