# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-17 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import internal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0295_venue_is_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='actpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='appcardtransaction',
            name='redpine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount that the user has paid to RedPine', max_digits=6, validators=[internal.validators.non_negative], verbose_name="RedPine's fee"),
        ),
        migrations.AlterField(
            model_name='appcardtransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has spent', max_digits=6, validators=[internal.validators.non_negative], verbose_name='Total purchase amount'),
        ),
        migrations.AlterField(
            model_name='appcashtransaction',
            name='redpine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount that the user has paid to RedPine', max_digits=6, validators=[internal.validators.non_negative], verbose_name="RedPine's fee"),
        ),
        migrations.AlterField(
            model_name='appcashtransaction',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has spent', max_digits=6, validators=[internal.validators.non_negative], verbose_name='Total purchase amount'),
        ),
        migrations.AlterField(
            model_name='band',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='min_ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='promoter_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=4, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_raised',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='The cached revenue total. Should be "None" until after the show date.', max_digits=6, null=True, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='organizationpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='redpine_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='The amount that the user has paid to RedPine', max_digits=6, validators=[internal.validators.non_negative], verbose_name="RedPine's fee"),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='total',
            field=models.DecimalField(decimal_places=2, help_text='The total amount that the user has spent', max_digits=6, validators=[internal.validators.non_negative], verbose_name='Total purchase amount'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='The amount to charge for this item', max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(default=100, help_text='The number of this item available for sale.', validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='min_headcount',
            field=models.IntegerField(default=0, validators=[internal.validators.non_negative]),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[internal.validators.non_negative]),
        ),
    ]
