# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-02 23:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0296_auto_20200217_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
