# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_spotifyconnection_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyconnection',
            name='access_token',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyconnection',
            name='client_id',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyconnection',
            name='refresh_token',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
