# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-02 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue_listings', '0002_auto_20190502_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name_plural': 'Provinces'},
        ),
    ]
