# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_listings', '0003_auto_20190502_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
