# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-27 22:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0010_charge_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='Square_response',
        ),
        migrations.AddField(
            model_name='charge',
            name='square_response',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}', null=True),
        ),
    ]
