# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0011_auto_20190327_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_id', models.CharField(help_text="The Square Card object's ID", max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='square.Customer')),
            ],
        ),
    ]
