# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-28 05:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0012_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='brand',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='exp_month',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='card',
            name='exp_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
