# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('square', '0013_auto_20190328_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=12),
        ),
    ]
