# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The user to send the email to', max_length=254)),
                ('model', models.CharField(help_text='The model to monitor', max_length=100)),
            ],
        ),
    ]
