# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_auto_20180205_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='fields',
            field=models.CharField(default='', help_text='Comma separated list of fields to serialize on the model', max_length=200),
        ),
    ]
