# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20180208_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='created_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='created_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
