# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20180208_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge_fact',
            old_name='quantity',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='pledge_fact',
            old_name='gross_amount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='pledge_fact',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='pledge_fact',
            name='created_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pledge_fact',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pledge_fact',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
