# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20180208_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign_fact',
            name='campaign_goal',
        ),
        migrations.AddField(
            model_name='campaign_fact',
            name='goal_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
