# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_campaign_success_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot_Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('archived', models.BooleanField(default=False)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('min_headcount', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('campaign_success', models.DateTimeField(null=True)),
                ('is_successful', models.NullBooleanField(choices=[(None, 'null'), (True, 'true'), (False, 'false')])),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Campaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='min_headcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timeslot_fact',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Timeslot'),
        ),
        migrations.AddField(
            model_name='timeslot_fact',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Venue'),
        ),
    ]
