# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20180209_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
