# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_auto_20190210_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='funding_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='funding_type',
            field=models.IntegerField(choices=[(0, 'GOAL_AMOUNT'), (1, 'GOAL_COUNT'), (2, 'HYBRID')], default=2),
        ),
    ]
